# Generated by Django 5.1.2 on 2024-10-24 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principalticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
